### ISSUE TITLE
cannot run example

### ISSUE THREAD

**Issue by mchikina** [MaayanLab/speedr#1]
From the example provided on github two of the commands fail

`libraries <- speedr::list_libraries()
Error in fromJSON(rawToChar(res$content)) : unexpected character '<'`

`res <- speedr::import_gmt("KEGG_2021_Human", gmt)
Error in curl::curl_fetch_memory(url, handle = handle) : 
  transfer closed with 178 bytes remaining to read`

**Comment by lachmann12** [comment]
The R package is for a different version of a self-hosted Enrichr API. The default Enrichr server does support background correction as well, but not custom upload of gene set libraries. You can use a very similar R package I just wrote that will work very similarly.

https://github.com/MaayanLab/backr

**Comment by mchikina** [comment]
Thanks for this. I am able to run the code with no errors. However, the p-values are identical whether I provide a background or not.
